export type Row = Record<string, string>;
export type Dataset = { name: string; columns: string[]; rows: Row[] };
export type FieldSemantic = 'customer identifier'|'transaction identifier'|'product identifier'|'date'|'revenue'|'cost'|'quantity'|'discount'|'channel'|'location'|'status'|'campaign'|'hours'|'invoice amount'|'subscription plan'|'returns'|'inventory'|'project identifier'|'service'|'employee'|'billable'|'marketing spend'|'unknown';
export type ColumnProfile = { name:string; type:string; missing:number; unique:number; whitespace:number; inconsistentCase:number; numericStrings:number; min?:number; max?:number; mean?:number; median?:number; dateMin?:string; dateMax?:string; identifier:boolean; coverage:number };
export type HealthFinding = { tone:'good'|'warning'; fact:string; evidence?:string; consequence?:string };
export type HealthReport = { score:number; rows:number; columns:number; duplicates:number; profiles:ColumnProfile[]; findings:HealthFinding[] };
export type Relationship = { left:string; right:string; leftColumn:string; rightColumn:string; strength:'Strong'|'Likely'|'Needs confirmation'|'Unresolved'; overlap:number; leftUnique:number; rightUnique:number; compatibleTypes:boolean; sampled:boolean; consequence:string };
export type SemanticOverride = Record<string,Record<string,FieldSemantic>>;

const clean=(v:string)=>v.trim();
export const norm=(v:string)=>clean(v).toLowerCase().replace(/[^a-z0-9]/g,'');
const empty=(v:string)=>!clean(v);
const numeric=(v:string)=>/^[-+]?[$£€]?\d[\d,]*(\.\d+)?%?$/.test(clean(v));
const numberValue=(v:string)=>Number(clean(v).replace(/[$£€,%]/g,''));
const dateValue=(v:string)=>{const t=Date.parse(clean(v));return Number.isNaN(t)?null:t};
const MAX_RELATIONSHIP_VALUES=1500;
const MAX_CANDIDATES_PER_DATASET=10;

export function parseCSV(text:string,name='upload.csv'):Dataset{
 const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.length))rows.push(row);row=[];cell=''}else cell+=c}
 row.push(cell);if(row.some(x=>x.length))rows.push(row);
 if(rows.length<2)throw new Error('This CSV needs a header row and at least one data row.');
 const columns=rows[0].map((h,i)=>clean(h)||`column_${i+1}`);
 return{name,columns,rows:rows.slice(1).map(r=>Object.fromEntries(columns.map((c,i)=>[c,r[i]??''])))};
}

export function profileDataset(data:Dataset):HealthReport{
 const duplicateKeys=new Set<string>();let duplicates=0;
 for(const row of data.rows){const k=JSON.stringify(data.columns.map(c=>clean(row[c]??'')));if(duplicateKeys.has(k))duplicates++;else duplicateKeys.add(k)}
 const profiles=data.columns.map(name=>{
  const raw=data.rows.map(r=>r[name]??''),values=raw.filter(v=>!empty(v)),lower=new Map<string,Set<string>>();
  values.forEach(v=>{const k=clean(v).toLowerCase();if(!lower.has(k))lower.set(k,new Set());lower.get(k)!.add(v)});
  const nums=values.filter(numeric).map(numberValue).filter(Number.isFinite),dates=values.map(dateValue).filter((x):x is number=>x!==null);
  let type='text';if(values.length&&nums.length/values.length>.85)type='number';else if(values.length&&dates.length/values.length>.85)type='date';else if(new Set(values.map(clean)).size<=Math.max(20,values.length*.2))type='category';
  const sorted=[...nums].sort((a,b)=>a-b),unique=new Set(values.map(clean)).size;
  return{name,type,missing:raw.length-values.length,unique,coverage:values.length/Math.max(raw.length,1),whitespace:values.filter(v=>v!==clean(v)).length,inconsistentCase:[...lower.values()].filter(s=>s.size>1).length,numericStrings:type==='number'?values.length:0,min:nums.length?Math.min(...nums):undefined,max:nums.length?Math.max(...nums):undefined,mean:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:undefined,median:nums.length?(sorted[Math.floor((sorted.length-1)/2)]+sorted[Math.ceil((sorted.length-1)/2)])/2:undefined,dateMin:dates.length?new Date(Math.min(...dates)).toISOString().slice(0,10):undefined,dateMax:dates.length?new Date(Math.max(...dates)).toISOString().slice(0,10):undefined,identifier:unique/Math.max(values.length,1)>.92&&/(^id$|_id$|code|number|num|key)/i.test(name)};
 });
 const total=Math.max(data.rows.length,1),missing=profiles.reduce((s,p)=>s+p.missing,0),whitespace=profiles.reduce((s,p)=>s+p.whitespace,0),inconsistent=profiles.reduce((s,p)=>s+p.inconsistentCase,0);
 const penalty=Math.min(65,Math.round(missing/(total*Math.max(data.columns.length,1))*45)+Math.round(duplicates/total*25)+Math.min(10,whitespace)+Math.min(10,inconsistent*2));
 const findings:HealthFinding[]=[];
 profiles.filter(p=>p.missing===0).slice(0,2).forEach(p=>findings.push({tone:'good',fact:`${p.name} is complete across all ${data.rows.length.toLocaleString()} rows.`,evidence:`100% of values in ${p.name} are non-null.`}));
 profiles.filter(p=>p.type==='number'&&p.missing===0).slice(0,1).forEach(p=>findings.push({tone:'good',fact:`${p.name} is consistently numeric and ready to summarize.`,evidence:'All observed non-null values were parsed as numbers.'}));
 profiles.filter(p=>p.missing>0).slice(0,3).forEach(p=>findings.push({tone:'warning',fact:`${p.name} is missing in ${p.missing} rows (${(p.missing/total*100).toFixed(1)}%).`,evidence:`${total-p.missing} of ${total} rows contain a value.`,consequence:`Analyses grouped by ${p.name} may undercount or classify some activity as unknown.`}));
 if(duplicates)findings.push({tone:'warning',fact:`${duplicates} duplicate row${duplicates===1?' was':'s were'} detected.`,evidence:'The duplicate rows contain identical values across every uploaded column.',consequence:'If these represent duplicate events rather than legitimate repeats, totals may be overstated.'});
 profiles.filter(p=>p.whitespace||p.inconsistentCase).slice(0,2).forEach(p=>findings.push({tone:'warning',fact:`${p.name} contains ${p.whitespace?'extra whitespace':''}${p.whitespace&&p.inconsistentCase?' and ':''}${p.inconsistentCase?'inconsistent capitalization':''}.`,evidence:`${p.whitespace+p.inconsistentCase} formatting inconsistency signal${p.whitespace+p.inconsistentCase===1?' was':'s were'} observed.`,consequence:'Comparisons may fragment one category into multiple labels.'}));
 return{score:100-penalty,rows:data.rows.length,columns:data.columns.length,duplicates,profiles,findings};
}

const semanticRules:[FieldSemantic,string[]][]=[
 ['customer identifier',['customer_id','customerid','client_id','clientid','account_num','account_id']],['transaction identifier',['order_id','transaction_id','sale_id','receipt_id']],['product identifier',['product_id','product_code','sku','item_id']],['date',['date','created_at','month','period','timestamp']],['revenue',['revenue','sales','net_sales','order_total']],['cost',['cost','cogs','unit_cost','expense']],['quantity',['quantity','qty','units']],['discount',['discount','promo']],['channel',['channel','source']],['location',['location','store','region']],['status',['status','state']],['campaign',['campaign']],['hours',['hours','duration']],['invoice amount',['invoice_amount','invoice_total','bill_amount']],['subscription plan',['plan','tier']],['returns',['return','refund']],['inventory',['inventory','stock','on_hand']],['project identifier',['project_id','project_code']],['service',['service','service_line']],['employee',['employee','consultant','staff']],['billable',['billable']],['marketing spend',['marketing_spend','ad_spend','spend']]
];
export const fieldSemanticOptions:FieldSemantic[]=['customer identifier','transaction identifier','product identifier','date','revenue','cost','quantity','discount','channel','location','status','campaign','hours','invoice amount','subscription plan','returns','inventory','project identifier','service','employee','billable','marketing spend','unknown'];
export function inferField(name:string,profile?:ColumnProfile):{semantic:FieldSemantic;confidence:'High confidence'|'Likely'|'Needs confirmation'}{
 for(const [semantic,aliases] of semanticRules){if(aliases.some(a=>norm(name)===norm(a)))return{semantic,confidence:'High confidence'}}
 for(const [semantic,aliases] of semanticRules){if(aliases.some(a=>norm(name).includes(norm(a))||norm(a).includes(norm(name))))return{semantic,confidence:'Likely'}}
 if(profile?.identifier)return{semantic:'transaction identifier',confidence:'Needs confirmation'};
 return{semantic:'unknown',confidence:'Needs confirmation'};
}

const roleRules:Record<string,string[]>={
 'Orders / Transactions':['order','transaction','revenue','quantity','sale'],'Customers':['customer','client','email'],'Products':['product','sku','category'],'Product Costs':['cost','unit_cost','cogs'],'Marketing':['campaign','spend','impression'],'Inventory':['inventory','stock','on_hand'],'Returns':['return','refund'],'Invoices':['invoice','payment'],'Expenses':['expense'],'Subscriptions':['subscription','plan','mrr','churn','renewal'],'Projects':['project','hours','billable','rate'],'Time Tracking':['timesheet','hours','billable'],'Locations':['location','store','region'],'Employees':['employee','staff'],'Service Records':['service','appointment','case']
};
export const roleOptions=['Orders / Transactions','Customers','Products','Product Costs','Marketing','Inventory','Returns','Invoices','Expenses','Subscriptions','Projects','Time Tracking','Locations','Employees','Service Records','Other / Unknown'];
export function inferRole(data:Dataset,override?:string){if(override)return{role:override,confidence:'User confirmed' as const};const names=[...data.columns.map(norm),norm(data.name)];let best='Other / Unknown',score=0;for(const [role,signals] of Object.entries(roleRules)){const s=signals.filter(t=>names.some(n=>n.includes(norm(t)))).length;if(s>score){score=s;best=role}}return{role:best,confidence:score>=3?'High confidence':score>=1?'Likely':'Needs confirmation'} as const}

function sampledValues(data:Dataset,column:string){const step=Math.max(1,Math.ceil(data.rows.length/MAX_RELATIONSHIP_VALUES));const values:string[]=[];for(let i=0;i<data.rows.length&&values.length<MAX_RELATIONSHIP_VALUES;i+=step){const v=norm(data.rows[i][column]||'');if(v)values.push(v)}return new Set(values)}
function candidateColumns(data:Dataset,profiles:ColumnProfile[],overrides?:Record<string,FieldSemantic>){return profiles.map(p=>({profile:p,semantic:overrides?.[p.name]||inferField(p.name,p).semantic})).filter(x=>x.profile.identifier||x.semantic.endsWith('identifier')).sort((a,b)=>Number(b.profile.identifier)-Number(a.profile.identifier)||b.profile.coverage-a.profile.coverage).slice(0,MAX_CANDIDATES_PER_DATASET)}
export function findRelationships(sets:Dataset[],semanticOverrides:SemanticOverride={}):Relationship[]{
 const profiles=sets.map(profileDataset),out:Relationship[]=[];
 for(let a=0;a<sets.length;a++)for(let b=a+1;b<sets.length;b++){
  const left=candidateColumns(sets[a],profiles[a].profiles,semanticOverrides[sets[a].name]),right=candidateColumns(sets[b],profiles[b].profiles,semanticOverrides[sets[b].name]);let best:{relation:Relationship;score:number}|null=null;
  for(const l of left)for(const r of right){const ln=norm(l.profile.name),rn=norm(r.profile.name),sameSemantic=l.semantic!=='unknown'&&l.semantic===r.semantic,nameSimilar=ln===rn||ln.includes(rn)||rn.includes(ln);if(!sameSemantic&&!nameSimilar)continue;const lv=sampledValues(sets[a],l.profile.name),rv=sampledValues(sets[b],r.profile.name);if(!lv.size||!rv.size)continue;const matches=[...lv].filter(v=>rv.has(v)).length,overlap=matches/Math.max(lv.size,rv.size),compatibleTypes=l.profile.type===r.profile.type||l.semantic===r.semantic,uniqueness=Math.max(l.profile.unique/Math.max(sets[a].rows.length,1),r.profile.unique/Math.max(sets[b].rows.length,1)),score=overlap+(sameSemantic?.22:0)+(nameSimilar?.18:0)+(compatibleTypes?.08:0)+(uniqueness>.8?.08:0),strength=score>=1?'Strong':score>=.65?'Likely':score>=.4?'Needs confirmation':'Unresolved',unmatched=Math.round((1-overlap)*100),relation:Relationship={left:sets[a].name,right:sets[b].name,leftColumn:l.profile.name,rightColumn:r.profile.name,strength,overlap,leftUnique:l.profile.unique/Math.max(sets[a].rows.length,1),rightUnique:r.profile.unique/Math.max(sets[b].rows.length,1),compatibleTypes,sampled:sets[a].rows.length>MAX_RELATIONSHIP_VALUES||sets[b].rows.length>MAX_RELATIONSHIP_VALUES,consequence:unmatched===0?'All sampled key values matched across these sources.':`${unmatched}% of sampled key values were unmatched; joined analysis may classify some records as unknown.`};if(!best||score>best.score)best={relation,score}}
  if(best&&best.relation.overlap>=.08)out.push(best.relation);
 }
 const weight={Strong:4,Likely:3,'Needs confirmation':2,Unresolved:1};return out.sort((x,y)=>weight[y.strength]-weight[x.strength]||y.overlap-x.overlap).slice(0,30);
}

export type Archetype='commerce'|'services'|'subscription'|'other';
export function inferBusinessContext(sets:Dataset[],roleOverrides:Record<string,string>={}):{archetype:Archetype;confidence:string;evidence:string[]}{const roles=sets.map(d=>inferRole(d,roleOverrides[d.name]).role),fields=sets.flatMap(d=>d.columns.map(c=>inferField(c).semantic));const scores={commerce:0,services:0,subscription:0,other:1};roles.forEach(r=>{if(/Orders|Products|Inventory|Returns|Costs/.test(r))scores.commerce+=2;if(/Projects|Time Tracking|Invoices|Service/.test(r))scores.services+=2;if(/Subscriptions/.test(r))scores.subscription+=3});fields.forEach(f=>{if(['product identifier','quantity','returns','inventory','discount'].includes(f))scores.commerce++;if(['project identifier','service','hours','billable','invoice amount'].includes(f))scores.services++;if(['subscription plan','status'].includes(f))scores.subscription++});const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]) as [Archetype,number][];return{archetype:ranked[0][1]>=2?ranked[0][0]:'other',confidence:ranked[0][1]-ranked[1][1]>=3?'High confidence':'Needs confirmation',evidence:roles.filter(r=>r!=='Other / Unknown').slice(0,4)}}

export type MetricDefinition={id:string;name:string;archetypes:Archetype[];description:string;required:FieldSemantic[][];optional:FieldSemantic[][];minCoverage:number;missing:string;unlockGroup:string;priority:number};
const m=(id:string,name:string,archetypes:Archetype[],description:string,required:FieldSemantic[][],missing:string,unlockGroup:string,priority=5,optional:FieldSemantic[][]=[]):MetricDefinition=>({id,name,archetypes,description,required,optional,minCoverage:.85,missing,unlockGroup,priority});
export const metricDefinitions:MetricDefinition[]=[
 m('revenue','Revenue',['commerce','services','subscription','other'],'Summarize recorded revenue.',[['revenue','invoice amount']],'Revenue or invoice amount is needed.','revenue data',10),m('trend','Trends over time',['commerce','services','subscription','other'],'Track meaningful measures over time.',[['date'],['revenue','invoice amount','quantity','hours']],'A usable date and numeric measure are needed.','usable dates',9),m('volume','Order volume',['commerce'],'Count transactions over time.',[['transaction identifier']],'Transaction identifiers are needed.','transaction identifiers',7),m('aov','Average order value',['commerce'],'Compare revenue per order.',[['transaction identifier'],['revenue']],'Order identifiers and revenue are needed.','transaction identifiers + revenue',7),m('product','Product performance',['commerce'],'Compare demand and sales by product.',[['product identifier'],['revenue','quantity']],'Product identifiers and revenue or quantity are needed.','product identifiers',9),m('margin','Gross margin',['commerce'],'Compare revenue with costs.',[['revenue'],['cost']],'Cost data is needed to calculate margin.','product costs',9),m('profit','Product profitability',['commerce'],'Compare product revenue with product costs.',[['product identifier'],['revenue'],['cost']],'Product identifiers, revenue, and cost are needed.','product costs',10),m('repeat','Repeat purchase rate',['commerce'],'Measure recurring customer activity.',[['customer identifier'],['transaction identifier'],['date']],'Customer, transaction, and date fields are needed.','customer identifiers',8),m('concentration','Customer concentration',['commerce','services','subscription','other'],'Measure reliance on top customers or groups.',[['customer identifier'],['revenue','invoice amount']],'Customer identifiers and revenue are needed.','customer identifiers',6),m('channel','Sales-channel performance',['commerce'],'Compare activity across sales channels.',[['channel'],['revenue','quantity']],'Channel and sales activity are needed.','channel data',7),m('returns','Return rate',['commerce'],'Measure returned activity.',[['returns'],['transaction identifier','product identifier']],'Return records and transaction or product identifiers are needed.','returns data',5),m('discount','Discount rate',['commerce'],'Measure discount frequency or value.',[['discount'],['revenue','transaction identifier']],'Discount and sales data are needed.','discount data',5),m('marketing','Marketing efficiency',['commerce'],'Connect marketing spend to resulting activity.',[['marketing spend'],['campaign'],['customer identifier','transaction identifier']],'Marketing spend, campaign, and credible attribution are needed.','marketing spend + attribution',4),
 m('clientRevenue','Revenue by client',['services'],'Compare client contribution.',[['customer identifier'],['revenue','invoice amount']],'Client identifiers and revenue are needed.','client identifiers',10),m('serviceRevenue','Revenue by service',['services'],'Compare service-line contribution.',[['service'],['revenue','invoice amount']],'Service and revenue fields are needed.','service identifiers',8),m('projectRevenue','Revenue by project',['services'],'Compare project contribution.',[['project identifier'],['revenue','invoice amount']],'Project identifiers and revenue are needed.','project identifiers',8),m('repeatClient','Repeat-client rate',['services'],'Measure recurring client work.',[['customer identifier'],['project identifier','transaction identifier'],['date']],'Client, engagement, and date fields are needed.','client and project identifiers',7),m('projectValue','Average project value',['services'],'Compare invoiced value per project.',[['project identifier'],['invoice amount','revenue']],'Project identifiers and invoice values are needed.','project identifiers + invoice values',7),m('projectProfit','Project profitability',['services'],'Compare project revenue with cost.',[['project identifier'],['revenue','invoice amount'],['cost']],'Project, revenue, and cost data are needed.','project costs',9),m('billable','Billable vs non-billable time',['services'],'Compare billable and non-billable hours.',[['hours'],['billable']],'Hours and billable status are needed.','billable time data',8),m('utilization','Utilization',['services'],'Measure billable share of recorded time.',[['hours'],['billable'],['employee']],'Hours, billable status, and employee data are needed.','employee time data',8),m('paymentTiming','Invoice/payment timing',['services'],'Assess billing and payment timing.',[['invoice amount'],['date'],['status']],'Invoice, date, and payment status fields are needed.','invoice status data',6),
 m('recurring','Recurring revenue',['subscription'],'Track recurring subscription value.',[['revenue'],['date'],['subscription plan']],'Recurring revenue, date, and plan fields are needed.','recurring revenue data',10),m('active','Active customers',['subscription'],'Count active subscription customers.',[['customer identifier'],['status']],'Customer identifiers and subscription status are needed.','subscription status',9),m('newSubs','New subscriptions',['subscription'],'Track newly started subscriptions.',[['customer identifier'],['date'],['subscription plan']],'Customer, start date, and plan are needed.','subscription start dates',8),m('churn','Churn',['subscription'],'Track cancellations.',[['customer identifier'],['status'],['date']],'Customer, cancellation/status, and date fields are needed.','cancellation data',9),m('retention','Retention',['subscription'],'Measure retained customers over time.',[['customer identifier'],['status'],['date']],'Customer, status, and date fields are needed.','subscription status history',9),m('planMix','Plan mix',['subscription'],'Compare customers or revenue by plan.',[['subscription plan'],['customer identifier','revenue']],'Plan plus customer or revenue data are needed.','subscription plan data',6),m('arpc','Average revenue per customer',['subscription'],'Compare recurring value per customer.',[['customer identifier'],['revenue']],'Customer and revenue fields are needed.','customer revenue data',8),
 m('category','Category performance',['other'],'Compare a measure across groups.',[['revenue','invoice amount','quantity','hours'],['channel','location','status','service']],'A numeric measure and grouping field are needed.','category fields',7),m('distribution','Distributions',['other'],'Understand the shape and spread of numeric values.',[['revenue','invoice amount','quantity','hours','cost']],'A numeric business measure is needed.','numeric measures',5),m('variance','Variance and comparisons',['other'],'Compare values across groups or periods.',[['revenue','invoice amount','quantity','hours'],['date','channel','location','status']],'A measure and comparison dimension are needed.','comparison dimensions',6),m('anomaly','Potential anomalies',['other'],'Surface unusual values for investigation.',[['revenue','invoice amount','quantity','hours','cost']],'A numeric measure is needed.','numeric measures',4)
];

function semanticInventory(sets:Dataset[],overrides:SemanticOverride){const found=new Map<FieldSemantic,{coverage:number;dataset:string;column:string}>();for(const data of sets){const report=profileDataset(data);for(const p of report.profiles){const semantic=overrides[data.name]?.[p.name]||inferField(p.name,p).semantic;if(semantic==='unknown')continue;const old=found.get(semantic);if(!old||p.coverage>old.coverage)found.set(semantic,{coverage:p.coverage,dataset:data.name,column:p.name})}}return found}
export function metricReadiness(sets:Dataset[],archetype:string,semanticOverrides:SemanticOverride={},relations:Relationship[]=[]){
 const context=(['commerce','services','subscription','other'].includes(archetype)?archetype:'other') as Archetype,inventory=semanticInventory(sets,semanticOverrides),relationQuality=relations.some(r=>r.strength==='Strong'||r.strength==='Likely');
 return metricDefinitions.filter(def=>def.archetypes.includes(context)).map(def=>{
  const matches=def.required.map(group=>group.map(f=>inventory.get(f)).filter(Boolean).sort((a,b)=>b!.coverage-a!.coverage)[0]),missingGroups=def.required.filter((_,i)=>!matches[i]),minCoverage=Math.min(...matches.filter(Boolean).map(x=>x!.coverage),1);
  let status:'ready'|'caution'|'unavailable'=missingGroups.length?'unavailable':minCoverage>=def.minCoverage?'ready':'caution';
  if(status==='ready'&&def.required.length>2&&sets.length>1&&!relationQuality)status='caution';
  const costRelation=relations.find(r=>/cost/i.test(r.left)||/cost/i.test(r.right));
  if(['margin','profit'].includes(def.id)&&status==='ready'&&costRelation&&costRelation.overlap<.85)status='caution';
  const marketingDataset=sets.find(d=>inferRole(d).role==='Marketing');
  const credibleAttribution=marketingDataset&&relations.some(r=>(r.left===marketingDataset.name||r.right===marketingDataset.name)&&[r.leftColumn,r.rightColumn].some(c=>['customer identifier','transaction identifier'].includes(inferField(c).semantic))&&(r.strength==='Strong'||r.strength==='Likely'));
  if(def.id==='marketing'&&!credibleAttribution)status='unavailable';
  const evidence=matches.filter(Boolean).map(x=>`${x!.column} in ${x!.dataset} (${Math.round(x!.coverage*100)}% populated)`).slice(0,3).join(' · ');
  const reason=def.id==='marketing'&&!credibleAttribution?'Marketing activity exists, but no reliable customer or transaction attribution relationship was established.':status==='ready'?`Required fields are available: ${evidence}.`:status==='caution'?`The required fields exist, but coverage or relationship reliability is incomplete. ${evidence}.`:def.missing;
  const impact=status==='caution'?'Results may exclude records with missing values or depend on a relationship that still needs confirmation.':undefined;
  return{...def,status,reason,impact,missingFields:missingGroups.map(g=>g[0]),rank:def.priority+(status==='ready'?4:status==='caution'?1:-5)+Math.round(minCoverage*2)}
 }).sort((a,b)=>b.rank-a.rank)
}
export function unlockSuggestions(results:ReturnType<typeof metricReadiness>){const map=new Map<string,string[]>();results.filter(r=>r.status==='unavailable').forEach(r=>{if(!map.has(r.unlockGroup))map.set(r.unlockGroup,[]);map.get(r.unlockGroup)!.push(r.name)});return[...map.entries()].map(([data,metrics])=>({data,metrics:metrics.slice(0,4)})).slice(0,5)}
