'use client';
import {useMemo,useState} from 'react';
import {Dataset,HealthReport,findRelationships,inferRole,metricReadiness,parseCSV,profileDataset} from './analytics';
import {cleanSample,sampleFiles} from './samples';
const pct=(n:number)=>`${Math.round(n*100)}%`; const baseName=(s:string)=>s.replace(/\.csv$/i,'').replace(/[_-]+/g,' ');
export default function LabClient(){
 const [datasets,setDatasets]=useState<Dataset[]>([]),[health,setHealth]=useState<HealthReport|null>(null),[healthName,setHealthName]=useState(''),[error,setError]=useState(''),[business,setBusiness]=useState('commerce');
 const relations=useMemo(()=>findRelationships(datasets),[datasets]);
 function setSingle(data:Dataset){setDatasets([data]);setHealth(profileDataset(data));setHealthName(data.name);setError('')}
 function useHealthSample(clean=false){try{setSingle(parseCSV(clean?cleanSample:sampleFiles['orders.csv'],clean?'clean-orders.csv':'messy-orders.csv'))}catch(e){setError((e as Error).message)}}
 function useBusinessSample(){const sets=Object.entries(sampleFiles).map(([name,text])=>parseCSV(text,name));setDatasets(sets);setHealth(profileDataset(sets[0]));setHealthName(sets[0].name);setError('')}
 async function upload(files:FileList|null,multiple=false){if(!files?.length)return;if([...files].some(f=>!f.name.toLowerCase().endsWith('.csv'))){setError('CSV is supported in this first version. Excel support is coming next.');return}if(files.length>5){setError('Choose up to five CSV files at a time.');return}try{const parsed=await Promise.all([...files].map(async f=>parseCSV(await f.text(),f.name)));if(multiple){setDatasets(parsed);setHealth(profileDataset(parsed[0]));setHealthName(parsed[0].name)}else setSingle(parsed[0]);setError('')}catch(e){setError((e as Error).message)}}
 const inferred=business==='infer'?(datasets.some(d=>inferRole(d).role==='Services')?'services':datasets.some(d=>inferRole(d).role==='Subscriptions')?'subscription':'commerce'):business;
 const readiness=useMemo(()=>metricReadiness(datasets,inferred),[datasets,inferred]); const groups={ready:readiness.filter(x=>x.status==='ready'),caution:readiness.filter(x=>x.status==='caution'),unavailable:readiness.filter(x=>x.status==='unavailable')};
 return <main className="labPage">
  <nav className="nav shell"><a className="brand" href="/"><span className="logoMark" aria-hidden="true"/> Tanvi Kinkhabwala</a><a className="textlink" href="/#work">← Back to portfolio</a></nav>
  <section className="labHero shell"><p className="eyebrow"><span/> Analytics Lab</p><h1>Data is rarely ready<br/>for <em>the answer.</em></h1><p>Explore what happens between having data and knowing what to do with it.</p><div className="labProgress"><a href="#health"><b>01</b><strong>Trust it</strong><span>Data health</span></a><i>↓</i><a href="#connect"><b>02</b><strong>Connect it</strong><span>Relationships</span></a><i>↓</i><a href="#readiness"><b>03</b><strong>Understand it</strong><span>Analysis readiness</span></a><i>↓</i><div aria-disabled="true"><b>04</b><strong>Act on it</strong><span>Coming later</span></div></div></section>
  <div className="privacyNotice shell"><strong>Portfolio experiment</strong><p>CSV files are processed entirely in your browser for this demonstration. Their contents are not uploaded to this site or placed in the URL. Excel support is planned for a later version.</p></div>
  {error&&<div className="labError shell" role="alert">{error}</div>}
  <section className="labExperience shell" id="health"><header><div><span>01 · Data health check</span><h2>Think your data<br/>is clean?</h2><p>Upload a CSV file and find out.</p></div><div className="labActions"><label className="uploadButton">Choose a CSV<input aria-label="Upload one CSV for a data health check" type="file" accept=".csv,text/csv" onChange={e=>upload(e.target.files)}/></label><button onClick={()=>useHealthSample(false)}>Try messy sample</button><button className="quietButton" onClick={()=>useHealthSample(true)}>Try clean sample</button></div></header>{!health?<EmptyState text="Choose a file or sample to generate a deterministic data-health report."/>:<HealthView report={health} name={healthName}/>}</section>
  <section className="labExperience shell darkLab" id="connect"><header><div><span>02 · Connect my data</span><h2>Data in ten<br/>different places?</h2><p>See whether your sources can work together.</p></div><div className="labActions"><label className="uploadButton lightUpload">Choose up to 5 CSVs<input aria-label="Upload up to five CSV files to connect" type="file" multiple accept=".csv,text/csv" onChange={e=>upload(e.target.files,true)}/></label><button onClick={useBusinessSample}>Try sample business data</button></div></header>{!datasets.length?<EmptyState text="Add related files to infer table roles, key relationships, and what the combined data enables."/>:<ConnectionView datasets={datasets} relations={relations}/>}</section>
  <section className="labExperience shell" id="readiness"><header><div><span>03 · Analysis readiness</span><h2>What could your data<br/>actually tell you?</h2><p>I&apos;ll identify the analyses your current data can support—and what is still missing.</p></div><label className="businessSelect">What type of business is this?<select value={business} onChange={e=>setBusiness(e.target.value)}><option value="commerce">Commerce / Retail</option><option value="services">Services</option><option value="subscription">Subscription / SaaS</option><option value="other">Other</option><option value="infer">Let the system infer</option></select></label></header>{!datasets.length?<EmptyState text="Use sample data above or upload at least one CSV to assess analysis readiness."/>:<ReadinessView groups={groups} inferred={inferred}/>}</section>
  <section className="futureLab shell"><p className="kicker">Coming next</p><h2>What deserves<br/>your attention?</h2><p>Once the data is trusted, connected, and understood, the next step is finding the opportunities hidden inside it.</p><span>Opportunity Scan · Coming soon</span></section>
  <footer className="footer shell"><div className="brand"><span className="logoMark" aria-hidden="true"/> Tanvi Kinkhabwala</div><p>Analytics Lab · Portfolio experiment</p><div><a href="/">Portfolio</a><a href="mailto:tanvikinkhabwala@gmail.com">Email</a></div></footer>
 </main>;
}
function EmptyState({text}:{text:string}){return <div className="labEmpty"><span>Awaiting data</span><p>{text}</p></div>}
function HealthView({report,name}:{report:HealthReport;name:string}){const good=report.findings.filter(f=>f.tone==='good'),warn=report.findings.filter(f=>f.tone==='warning');return <div className="healthReport" aria-live="polite"><div className="healthScore"><span>Overall data health</span><strong>{report.score}<small>/100</small></strong><p>Transparent internal heuristic based on completeness, duplicates, and consistency checks.</p><div><b>{report.rows.toLocaleString()}</b> rows <b>{report.columns}</b> columns <b>{report.duplicates}</b> duplicates</div></div><div className="healthFindings"><h3>{name}</h3><section><h4>Looks good</h4>{good.length?good.map((f,i)=><article key={i}><b>✓ Detected</b><p>{f.fact}</p></article>):<p>No strong positive checks were available yet.</p>}</section><section><h4>Needs attention</h4>{warn.length?warn.map((f,i)=><article key={i}><b>⚠ Observed fact</b><p>{f.fact}</p>{f.consequence&&<aside><strong>Possible analytical consequence</strong>{f.consequence}</aside>}</article>):<p>No material issues were detected by the current checks.</p>}</section></div><details className="profileDetails"><summary>View column profile <span>+</span></summary><div>{report.profiles.map(p=><article key={p.name}><strong>{p.name}</strong><span>{p.type}</span><small>{p.missing} missing · {p.unique} unique{p.dateMin?` · ${p.dateMin} to ${p.dateMax}`:''}{p.mean!==undefined?` · mean ${p.mean.toFixed(1)}`:''}</small></article>)}</div></details></div>}
function ConnectionView({datasets,relations}:{datasets:Dataset[];relations:ReturnType<typeof findRelationships>}){return <div className="connectionResult" aria-live="polite"><div className="tableRoles"><h3>Here&apos;s what I think you uploaded</h3>{datasets.map(d=>{const r=inferRole(d);return <article key={d.name}><span>{baseName(d.name)}</span><strong>{r.role}</strong><small>{r.confidence}</small><p>{d.rows.length} rows · {d.columns.slice(0,5).join(' · ')}</p></article>})}</div><div className="relationshipModel"><h3>Likely connections</h3>{relations.length?relations.slice(0,6).map((r,i)=><article key={i} className={r.strength.toLowerCase()}><div><strong>{baseName(r.left)}</strong><span>{r.leftColumn}</span></div><i>↔</i><div><strong>{baseName(r.right)}</strong><span>{r.rightColumn}</span></div><p><b>{r.strength} relationship</b>{pct(r.overlap)} key overlap</p><aside><strong>Possible consequence</strong>{r.consequence}</aside></article>):<div className="noRelationship"><strong>Relationships cannot be confirmed.</strong><p>No pair of fields has enough naming, type, and value-overlap evidence. That is useful to know before combining these files.</p></div>}</div><div className="connectionEnables"><h3>With these sources, you could explore</h3><ul>{['Product profitability','Repeat-purchase behavior','Sales trends','Channel performance'].map(x=><li key={x}>✓ {x}</li>)}</ul><h4>Still limited</h4><p>○ Marketing ROI <span>Reliable order/customer attribution was not detected.</span></p><p>○ Inventory efficiency <span>Inventory or stock-level data was not provided.</span></p></div></div>}
function ReadinessView({groups,inferred}:{groups:Record<string,ReturnType<typeof metricReadiness>>;inferred:string}){const top=[...groups.ready,...groups.caution].slice(0,3);return <div className="readinessResult" aria-live="polite"><p className="contextGuess">Context used: <strong>{inferred==='commerce'?'Commerce / Retail':inferred==='subscription'?'Subscription / SaaS':inferred==='services'?'Services':'Other'}</strong></p><div className="readinessGroups"><MetricGroup title="Ready to analyze" mark="✓" items={groups.ready}/><MetricGroup title="Possible, with caution" mark="⚠" items={groups.caution}/><MetricGroup title="Not yet possible" mark="○" items={groups.unavailable}/></div><div className="analysisPlan"><span>Analysis plan—not a business recommendation</span><h3>Here&apos;s what I would analyze first.</h3>{top.length?top.map((m,i)=><article key={m.id}><b>0{i+1}</b><div><strong>{m.name}</strong><p>{m.status==='ready'?m.description:m.reason}</p></div></article>):<p>I can&apos;t reliably propose an analysis plan from the fields provided.</p>}</div></div>}
function MetricGroup({title,mark,items}:{title:string;mark:string;items:ReturnType<typeof metricReadiness>}){return <section><h3>{title}</h3>{items.length?items.map(m=><article key={m.id}><b>{mark}</b><div><strong>{m.name}</strong><p>{m.status==='ready'?m.description:m.reason}</p></div></article>):<p className="noneReady">No analyses in this group.</p>}</section>}
