'use client';
import {useMemo,useState} from 'react';
import {Dataset,FieldSemantic,HealthReport,Relationship,SemanticOverride,fieldSemanticOptions,findRelationships,inferBusinessContext,inferField,inferRole,metricReadiness,parseCSV,profileDataset,roleOptions,unlockSuggestions} from './analytics';
import {cleanSample,sampleFiles} from './samples';

const pct=(n:number)=>`${Math.round(n*100)}%`;
const baseName=(s:string)=>s.replace(/\.csv$/i,'').replace(/[_-]+/g,' ');
const contextName=(s:string)=>s==='commerce'?'Commerce / Retail':s==='subscription'?'Subscription / SaaS':s==='services'?'Services':'Other / General Business';

export default function LabClient(){
 const [datasets,setDatasets]=useState<Dataset[]>([]),[health,setHealth]=useState<HealthReport|null>(null),[healthName,setHealthName]=useState(''),[error,setError]=useState(''),[business,setBusiness]=useState('infer'),[chooseContext,setChooseContext]=useState(false),[roleOverrides,setRoleOverrides]=useState<Record<string,string>>({}),[semanticOverrides,setSemanticOverrides]=useState<SemanticOverride>({});
 const relations=useMemo(()=>findRelationships(datasets,semanticOverrides),[datasets,semanticOverrides]);
 const contextGuess=useMemo(()=>inferBusinessContext(datasets,roleOverrides),[datasets,roleOverrides]);
 const context=business==='infer'?contextGuess.archetype:business;
 const readiness=useMemo(()=>metricReadiness(datasets,context,semanticOverrides,relations),[datasets,context,semanticOverrides,relations]);
 const groups={ready:readiness.filter(x=>x.status==='ready'),caution:readiness.filter(x=>x.status==='caution'),unavailable:readiness.filter(x=>x.status==='unavailable')};
 const sampled=relations.some(r=>r.sampled);
 function acceptDatasets(parsed:Dataset[]){setDatasets(parsed);setHealth(profileDataset(parsed[0]));setHealthName(parsed[0].name);setRoleOverrides({});setSemanticOverrides({});setBusiness('infer');setChooseContext(false);setError('')}
 function setSingle(data:Dataset){acceptDatasets([data])}
 function useHealthSample(clean=false){try{setSingle(parseCSV(clean?cleanSample:sampleFiles['orders.csv'],clean?'clean-orders.csv':'messy-orders.csv'))}catch(e){setError((e as Error).message)}}
 function useBusinessSample(){acceptDatasets(Object.entries(sampleFiles).map(([name,text])=>parseCSV(text,name)))}
 async function upload(files:FileList|null,multiple=false){if(!files?.length)return;const list=[...files];if(list.some(f=>!f.name.toLowerCase().endsWith('.csv'))){setError('CSV is supported in this version. Excel support is planned for later.');return}if(list.length>15){setError('Choose up to 15 CSV files at a time.');return}if(list.some(f=>f.size>25*1024*1024)||list.reduce((s,f)=>s+f.size,0)>75*1024*1024){setError('For a responsive browser experience, each CSV must be 25 MB or smaller and the combined upload must be 75 MB or smaller. No files were analyzed.');return}try{const parsed=await Promise.all(list.map(async f=>parseCSV(await f.text(),f.name)));if(multiple)acceptDatasets(parsed);else setSingle(parsed[0])}catch(e){setError((e as Error).message)}}
 function setRole(file:string,role:string){setRoleOverrides(v=>({...v,[file]:role}))}
 function setSemantic(file:string,column:string,semantic:FieldSemantic){setSemanticOverrides(v=>({...v,[file]:{...(v[file]||{}),[column]:semantic}}))}
 return <main className="labPage">
  <nav className="nav shell"><a className="brand" href="/"><span className="logoMark" aria-hidden="true"/> Tanvi Kinkhabwala</a><a className="textlink" href="/#work">← Back to portfolio</a></nav>
  <section className="labHero shell"><p className="eyebrow"><span/> Analytics Lab</p><h1>Data is rarely ready<br/>for <em>the answer.</em></h1><p>Follow the analytical journey from trust, to connection, to what the data can reliably support.</p><div className="labProgress"><a href="#health"><b>01</b><strong>Trust it</strong><span>Data health</span></a><i>↓</i><a href="#connect"><b>02</b><strong>Connect it</strong><span>Relationships</span></a><i>↓</i><a href="#readiness"><b>03</b><strong>Understand it</strong><span>Analysis readiness</span></a><i>↓</i><div aria-disabled="true"><b>04</b><strong>Act on it</strong><span>Coming later</span></div></div></section>
  <div className="privacyNotice shell"><strong>Local browser analysis</strong><p>Your files are analyzed locally in your browser and are not uploaded to a server. They remain available only in this active page session. Relationship checks may use a disclosed sample for large tables; profiling uses the full uploaded file.</p></div>
  {error&&<div className="labError shell" role="alert">{error}</div>}
  {datasets.length>0&&<div className="journeyState shell" aria-live="polite"><span>Active session</span><strong>{datasets.length} dataset{datasets.length===1?'':'s'} available across all three steps</strong><p>Upload once, then continue through Trust → Connect → Understand.</p></div>}
  <section className="labExperience shell" id="health"><header><div><span>01 · Data health check</span><h2>Can I trust<br/>this data?</h2><p>Profile one CSV, identify quality signals, and understand why they may matter.</p></div><div className="labActions"><label className="uploadButton">Choose a CSV<input aria-label="Upload one CSV for a data health check" type="file" accept=".csv,text/csv" onChange={e=>upload(e.target.files)}/></label><button onClick={()=>useHealthSample(false)}>Try messy sample</button><button className="quietButton" onClick={()=>useHealthSample(true)}>Try clean sample</button></div></header>{!health?<EmptyState text="Choose a file or sample to generate a deterministic data-health report."/>:<HealthView report={health} name={healthName}/>}</section>
  <section className="labExperience shell darkLab" id="connect"><header><div><span>02 · Connect my data</span><h2>Can these sources<br/>work together?</h2><p>Profile schemas first, then test only plausible key relationships.</p></div><div className="labActions"><label className="uploadButton lightUpload">Choose up to 15 CSVs<input aria-label="Upload up to fifteen CSV files to connect" type="file" multiple accept=".csv,text/csv" onChange={e=>upload(e.target.files,true)}/></label><button onClick={useBusinessSample}>Try sample business data</button></div></header>{sampled&&<p className="samplingNotice"><strong>Sampling disclosed:</strong> relationship overlap uses up to 1,500 evenly spaced values per candidate key. Full-file profiling is unchanged.</p>}{!datasets.length?<EmptyState text="Add related files to infer table roles, useful fields, and relationships. The same files continue into Analysis Readiness."/>:<ConnectionView datasets={datasets} relations={relations} roleOverrides={roleOverrides} semanticOverrides={semanticOverrides} setRole={setRole} setSemantic={setSemantic}/>}</section>
  <section className="labExperience shell" id="readiness"><header><div><span>03 · Analysis readiness</span><h2>What can I actually<br/>learn from this?</h2><p>Confirm the context, then see which analyses are supported, questionable, or blocked.</p></div><label className="businessSelect">Choose the business context<select value={business} onChange={e=>{setBusiness(e.target.value);setChooseContext(false)}}><option value="infer">Let the system infer</option><option value="commerce">Commerce / Retail</option><option value="services">Services</option><option value="subscription">Subscription / SaaS</option><option value="other">Other / General Business</option></select></label></header>{!datasets.length?<EmptyState text="Use sample data above or upload at least one CSV to assess analysis readiness."/>:<><div className="contextConfirm"><span>Inferred—not observed</span><p>I think this data looks like:</p><strong>{contextName(contextGuess.archetype)}</strong><small>{contextGuess.confidence}{contextGuess.evidence.length?` · Signals: ${contextGuess.evidence.join(', ')}`:''}</small><div><button onClick={()=>{setBusiness(contextGuess.archetype);setChooseContext(false)}}>Yes, that&apos;s right</button><button className="quietButton" onClick={()=>setChooseContext(true)}>Choose another</button></div>{chooseContext&&<label>Use this context<select value={business==='infer'?contextGuess.archetype:business} onChange={e=>{setBusiness(e.target.value);setChooseContext(false)}}><option value="commerce">Commerce / Retail</option><option value="services">Services</option><option value="subscription">Subscription / SaaS</option><option value="other">Other / General Business</option></select></label>}</div><ReadinessView groups={groups} context={context}/></>}</section>
  <section className="futureLab shell"><p className="kicker">04 · Opportunity Scan · Coming next</p><h2>What deserves<br/>attention?</h2><p>A future step will use confirmed context, semantic mappings, relationships, eligible metrics, quality scores, and reliability evidence to surface areas worth investigating—not automatic recommendations.</p><span>Act · Coming soon</span></section>
  <footer className="footer shell"><div className="brand"><span className="logoMark" aria-hidden="true"/> Tanvi Kinkhabwala</div><p>Analytics Lab · Portfolio experiment</p><div><a href="/">Portfolio</a><a href="mailto:tanvikinkhabwala@gmail.com">Email</a></div></footer>
 </main>
}

function EmptyState({text}:{text:string}){return <div className="labEmpty"><span>Awaiting data</span><p>{text}</p></div>}
function HealthView({report,name}:{report:HealthReport;name:string}){
 const good=report.findings.filter(f=>f.tone==='good').slice(0,5),warn=report.findings.filter(f=>f.tone==='warning').slice(0,8),dates=report.profiles.filter(p=>p.dateMin&&p.dateMax),dateMin=dates.map(p=>p.dateMin!).sort()[0],dateMax=dates.map(p=>p.dateMax!).sort().at(-1),missing=report.profiles.reduce((sum,p)=>sum+p.missing,0),duplicateRate=report.duplicates/Math.max(report.rows,1),identifiers=report.profiles.filter(p=>p.identifier).length;
 const interpretation=report.score>=90?'Strong data foundation':report.score>=75?'Usable, with several issues worth addressing':report.score>=50?'Significant quality issues may affect analysis':'Substantial cleanup is needed before reliable analysis';
 const impacts=warn.filter(f=>f.consequence).map(f=>({title:impactTitle(f.fact),copy:f.consequence!})).filter((x,i,a)=>a.findIndex(y=>y.title===x.title)===i).slice(0,5);
 const summaries=[{label:'Rows',value:report.rows.toLocaleString()},{label:'Columns',value:String(report.columns)},...(dateMin&&dateMax?[{label:'Date range',value:`${dateMin} — ${dateMax}`}]:[]),...(report.duplicates?[{label:'Duplicates',value:`${report.duplicates.toLocaleString()} · ${pct(duplicateRate)}`}]:[]),...(missing?[{label:'Missing values',value:missing.toLocaleString()}]:[]),...(!missing&&identifiers?[{label:'Likely IDs',value:String(identifiers)}]:[])];
 return <div className="healthReport" aria-live="polite"><h3 className="datasetName" title={name}>{name}</h3><div className="healthPrimary"><section className="healthScore"><span>Overall data health</span><strong>{report.score}<small>/100</small></strong><div className="scoreBar" aria-label={`Data health score ${report.score} out of 100`}><i style={{width:`${report.score}%`}}/></div><h4>{interpretation}</h4><p>Score is an internal heuristic based on completeness, duplicates, consistency, and other data-quality checks.</p></section><div className="healthCenter"><div className="summaryRow">{summaries.map(x=><article key={x.label}><span>{x.label}</span><strong>{x.value}</strong></article>)}</div><div className="findingPanels"><section className="goodPanel"><h4><span aria-hidden="true">✓</span> Looks good</h4>{good.length?good.map((f,i)=><div className="goodRow" key={i}><span aria-hidden="true">✓</span><p>{f.fact}</p></div>):<p className="emptyFinding">No strong positive checks were available yet.</p>}</section><section className="attentionPanel"><h4><span aria-hidden="true">⚠</span> Needs attention</h4>{warn.length?warn.map((f,i)=><IssueRow key={i} finding={f}/>):<p className="emptyFinding">No material issues were detected by the current checks.</p>}</section></div></div><aside className="impactPanel"><h4><span aria-hidden="true">◎</span> Impact on analysis</h4>{impacts.length?impacts.map((x,i)=><article key={i}><strong>{x.title}</strong><p>{x.copy}</p></article>):<article><strong>No major analytical impacts detected</strong><p>The current checks did not find material issues likely to affect analysis.</p></article>}<div><strong>What this score means</strong><p>{interpretation}. Addressing the highlighted issues can improve analytical reliability.</p></div></aside></div><ColumnOverview report={report}/></div>
}
function impactTitle(fact:string){const f=fact.toLowerCase();if(f.includes('customer'))return'Customer analysis may be incomplete';if(f.includes('duplicate'))return'Totals may be overstated';if(f.includes('product')||f.includes('capitalization')||f.includes('whitespace'))return'Category comparisons may be fragmented';if(f.includes('date'))return'Trends may be distorted';if(f.includes('revenue')||f.includes('numeric'))return'Financial summaries may be affected';return'Grouped analysis may be incomplete'}
function IssueRow({finding}:{finding:HealthReport['findings'][number]}){const [open,setOpen]=useState(false);return <article className="issueRow"><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span aria-hidden="true">⚠</span><strong>{finding.fact}</strong><i aria-hidden="true">{open?'−':'+'}</i></button>{open&&<div><span>Observed</span><p>{finding.evidence||finding.fact}</p>{finding.consequence&&<><span>Why it may matter</span><p>{finding.consequence}</p></>}</div>}</article>}
function ColumnOverview({report}:{report:HealthReport}){return <details className="columnOverview"><summary>Column overview <span>View detailed profile +</span></summary><div className="columnTable" role="table" aria-label="Column profile"><div className="columnHead" role="row"><b>Column</b><b>Type</b><b>Completeness</b><b>Unique</b><b>Issues</b><b>Example values</b></div>{report.profiles.map(p=>{const issues=[p.missing?`${p.missing} missing`:'',p.whitespace?'extra whitespace':'',p.inconsistentCase?'inconsistent case':''].filter(Boolean);return <div className="columnRow" role="row" key={p.name}><strong>{p.name}</strong><span>{p.type}</span><span><b>{pct(p.coverage)}</b><i><em style={{width:`${Math.round(p.coverage*100)}%`}}/></i></span><span>{pct(p.unique/Math.max(report.rows-p.missing,1))}</span><span className={issues.length?'columnIssue':'columnClean'}>{issues.length?`⚠ ${issues.join(', ')}`:'✓ No issue detected'}</span><span title={p.examples.join(', ')}>{p.examples.join(', ')||'—'}</span></div>})}</div></details>}

type ConnectionProps={datasets:Dataset[];relations:Relationship[];roleOverrides:Record<string,string>;semanticOverrides:SemanticOverride;setRole:(f:string,r:string)=>void;setSemantic:(f:string,c:string,s:FieldSemantic)=>void};
function ConnectionView({datasets,relations,roleOverrides,semanticOverrides,setRole,setSemantic}:ConnectionProps){return <div className="connectionResult" aria-live="polite"><div className="tableRoles"><h3>Dataset understanding</h3>{datasets.map(d=>{const report=profileDataset(d),r=inferRole(d,roleOverrides[d.name]);return <article key={d.name}><span>{baseName(d.name)}</span><strong>{r.role}</strong><small>Inferred · {r.confidence}</small><p>Observed · {d.rows.length.toLocaleString()} rows · {d.columns.length} columns</p><label>Correct table purpose<select value={r.role} onChange={e=>setRole(d.name,e.target.value)}>{roleOptions.map(x=><option key={x}>{x}</option>)}</select></label><details><summary>Review field meanings <span>+</span></summary><div className="semanticList">{report.profiles.map(p=>{const guess=inferField(p.name,p),value=semanticOverrides[d.name]?.[p.name]||guess.semantic;return <label key={p.name}><span><b>{p.name}</b><small>Observed · {pct(p.coverage)} populated · {p.type}</small></span><select value={value} onChange={e=>setSemantic(d.name,p.name,e.target.value as FieldSemantic)}>{fieldSemanticOptions.map(x=><option key={x}>{x}</option>)}</select><em>Inferred · {guess.confidence}</em></label>})}</div></details></article>})}</div><div className="relationshipModel"><h3>Relationship evidence</h3>{relations.length?relations.slice(0,15).map((r,i)=><article key={i} className={r.strength.toLowerCase().replace(' ','-')}><div><strong>{baseName(r.left)}</strong><span>{r.leftColumn}</span></div><i>↔</i><div><strong>{baseName(r.right)}</strong><span>{r.rightColumn}</span></div><p><b>{r.strength}</b>{pct(r.overlap)} value overlap</p><details><summary>Why this state? <span>+</span></summary><ul><li>{pct(r.overlap)} sampled value overlap</li><li>{pct(Math.max(r.leftUnique,r.rightUnique))} uniqueness on the more key-like side</li><li>{r.compatibleTypes?'Compatible':'Potentially incompatible'} detected data types</li></ul><aside><strong>Limitation</strong>{r.consequence}</aside></details></article>):<div className="noRelationship"><strong>I don&apos;t know how these files connect yet.</strong><p>No plausible keys had enough naming, type, uniqueness, and overlap evidence. Confirm field meanings above or provide a shared identifier.</p></div>}</div></div>}

function ReadinessView({groups,context}:{groups:Record<string,ReturnType<typeof metricReadiness>>;context:string}){const all=[...groups.ready,...groups.caution,...groups.unavailable],top=[...groups.ready,...groups.caution].sort((a,b)=>b.rank-a.rank).slice(0,3),unlocks=unlockSuggestions(all);return <div className="readinessResult" aria-live="polite"><p className="contextGuess">Context used: <strong>{contextName(context)}</strong>{context!=='other'&&' · User selection overrides inference'}</p><div className="readinessGroups"><MetricGroup title="Ready to analyze" mark="✓" items={groups.ready}/><MetricGroup title="Possible, with caution" mark="⚠" items={groups.caution}/><MetricGroup title="Not yet possible" mark="○" items={groups.unavailable}/></div>{unlocks.length>0&&<div className="unlockPanel"><span>What additional data would unlock</span><h3>Make more analysis possible.</h3>{unlocks.map(x=><article key={x.data}><strong>Add {x.data}</strong><p>Unlock: {x.metrics.join(' · ')}</p></article>)}</div>}<div className="analysisPlan"><span>Analysis plan—not a business recommendation</span><h3>Here&apos;s where I would start.</h3>{top.length?top.map((m,i)=><article key={m.id}><b>0{i+1}</b><div><strong>{m.name}</strong><p>{m.reason}</p></div></article>):<p>I can&apos;t reliably propose an analysis plan from the fields provided.</p>}</div></div>}
function MetricGroup({title,mark,items}:{title:string;mark:string;items:ReturnType<typeof metricReadiness>}){return <section><h3>{title}</h3>{items.length?items.map(m=><article key={m.id}><b>{mark}</b><div><strong>{m.name}</strong><p><span>{m.status==='unavailable'?'Missing':'Why'}:</span> {m.reason}</p>{m.impact&&<small><strong>Impact:</strong> {m.impact}</small>}</div></article>):<p className="noneReady">No analyses in this group.</p>}</section>}
