import {Dataset,HealthReport,SemanticOverride,inferField,norm} from './analytics';

export type OpportunityFinding={id:string;category:'OPPORTUNITY'|'RISK'|'CHANGE'|'MISMATCH'|'CONCENTRATION'|'ANOMALY'|'DATA LIMITATION';title:string;evidence:{value:string;label:string}[];why:string;confidence:'HIGH'|'MODERATE'|'LIMITED';unknown:string;next:string;dimensions:string[];limitation?:string};
type Eligible={id:string;name:string;status:string};
const number=(v:string)=>Number((v||'').replace(/[$£€,%]/g,'').replace(/,/g,''));
const pretty=(n:number)=>Math.abs(n)>=1e6?`$${(n/1e6).toFixed(1)}M`:Math.abs(n)>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${Math.round(n).toLocaleString()}`;

function column(data:Dataset,semantic:string,overrides:SemanticOverride){return data.columns.find(c=>(overrides[data.name]?.[c]||inferField(c).semantic)===semantic)}
function confidence(reports:HealthReport[],status:string,observations:number){const score=reports.length?reports.reduce((s,r)=>s+r.score,0)/reports.length:0;if(status==='caution'||score<75||observations<8)return'LIMITED' as const;if(score>=88&&observations>=20)return'HIGH' as const;return'MODERATE' as const}

/** Deterministic scan: every finding is produced by an explicit threshold over uploaded rows. */
export function opportunityScan(datasets:Dataset[],reports:HealthReport[],eligible:Eligible[],overrides:SemanticOverride):OpportunityFinding[]{
 const findings:OpportunityFinding[]=[];const allowed=new Map(eligible.filter(x=>x.status!=='unavailable').map(x=>[x.id,x.status]));
 const transaction=datasets.find(d=>column(d,'revenue',overrides));
 if(!transaction)return findings;
 const revenue=column(transaction,'revenue',overrides),date=column(transaction,'date',overrides),product=column(transaction,'product identifier',overrides),customer=column(transaction,'customer identifier',overrides),channel=column(transaction,'channel',overrides);
 const numericRows=transaction.rows.map(r=>({r,value:number(r[revenue!]||'')})).filter(x=>Number.isFinite(x.value));
 if(allowed.has('trend')&&date&&numericRows.length>=4){const periods=new Map<string,number>();numericRows.forEach(x=>{const p=(x.r[date]||'').slice(0,7);if(p)periods.set(p,(periods.get(p)||0)+x.value)});const ordered=[...periods.entries()].sort();if(ordered.length>=2){const first=ordered[0],last=ordered.at(-1)!,change=first[1]?last[1]/first[1]-1:0;if(Math.abs(change)>=.2)findings.push({id:'trend-change',category:'CHANGE',title:`Recorded revenue ${change>0?'increased':'decreased'} materially across the available period.`,evidence:[{value:`${change>0?'+':''}${Math.round(change*100)}%`,label:`${first[0]} → ${last[0]}`},{value:pretty(last[1]),label:'Latest period revenue'}],why:'The first-to-last period change exceeds the 20% materiality threshold.',confidence:confidence(reports,allowed.get('trend')!,numericRows.length),unknown:'Seasonality, promotions, market conditions, and operational capacity are not represented.',next:`Compare the change by ${channel?'channel':product?'product':'available segment'} and validate whether it is sustained.`,dimensions:[channel?'By channel':'',product?'By product':'','Over time'].filter(Boolean)})}}
 const segment=product||customer||channel;if(allowed.has(product?'product':customer?'concentration':'channel')&&segment&&numericRows.length>=4){const totals=new Map<string,number>();numericRows.forEach(x=>{const k=x.r[segment]||'Unknown';totals.set(k,(totals.get(k)||0)+x.value)});const ranked=[...totals.entries()].sort((a,b)=>b[1]-a[1]),total=ranked.reduce((s,x)=>s+x[1],0),share=total?ranked[0][1]/total:0;if(ranked.length>1&&share>=.35)findings.push({id:'concentration',category:'CONCENTRATION',title:`${ranked[0][0]} accounts for a large share of recorded revenue.`,evidence:[{value:`${Math.round(share*100)}%`,label:'Share of revenue'},{value:pretty(ranked[0][1]),label:'Recorded revenue'}],why:'The leading segment contributes at least 35% of the measured total.',confidence:confidence(reports,allowed.get(product?'product':customer?'concentration':'channel')||'caution',numericRows.length),unknown:'Strategic role, market size, capacity, and planned activity are not represented.',next:`Compare contribution, growth, and repeat behavior for ${ranked[0][0]} against the rest.`,dimensions:[product?'By product':'',channel?'By channel':'',customer?'By customer':'','Over time'].filter(Boolean)})}
 if(allowed.has('anomaly')||numericRows.length>=8){const values=numericRows.map(x=>x.value).sort((a,b)=>a-b),median=values[Math.floor(values.length/2)],deviations=values.map(v=>Math.abs(v-median)).sort((a,b)=>a-b),mad=deviations[Math.floor(deviations.length/2)]||1,max=Math.max(...values),score=Math.abs(max-median)/(1.4826*mad);if(score>=3.5)findings.push({id:'outlier',category:'ANOMALY',title:'One transaction is unusually large relative to the typical record.',evidence:[{value:pretty(max),label:'Largest transaction'},{value:`${score.toFixed(1)}×`,label:'Robust deviation score'}],why:'The largest value exceeds the 3.5 robust-deviation threshold based on the median absolute deviation.',confidence:confidence(reports,'ready',numericRows.length),unknown:'The data does not indicate whether this is a legitimate large order, correction, or entry error.',next:'Validate the source record, then compare its product, customer, and channel context.',dimensions:[product?'By product':'',customer?'By customer':'',channel?'By channel':''].filter(Boolean)})}
 const caution=eligible.find(x=>x.status==='caution');if(caution&&findings.length<4)findings.push({id:`limitation-${norm(caution.id)}`,category:'DATA LIMITATION',title:`${caution.name} may contain a useful pattern, but the current evidence is incomplete.`,evidence:[{value:'CAUTION',label:'Inherited readiness status'}],why:'The analysis is eligible only with caution because upstream coverage or relationship reliability is incomplete.',confidence:'LIMITED',unknown:'Records excluded by missing values or uncertain joins could change the observed result.',next:`Improve the limiting coverage, then rerun ${caution.name.toLowerCase()} before drawing a conclusion.`,dimensions:[],limitation:'This finding inherits its limitation from Analysis Readiness.'});
 return findings.slice(0,6);
}
